os:
  - linux
services:
  - docker
language: node_js
node_js:
  - 12.16.1
cache:
  directories:
    - node
    - node_modules
    - '$HOME/.gradle'
env:
  global:
    - NODE_VERSION=12.16.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
    - secure: bKhszvHH5MeRPeTQYS0uZJA8S9clHdoNRRvJEb0R9SStNqopY1Zb8ZfhKMtX2Oq004iDx+BWMnjBkhgF0HxT3Qey6fCOOpPCV9H21wfiUWpdOloPiFyqHZAxQxh2o/mzuD12RQCguqD2J8BvTgxc65fcEIYNBgIhCSj6qYnFFIM5vJs30gDD6O1BKmd5HKVGJDsFzFSAPKg4IIVOoKMt1xnUiJJBcmzCMCIxqQeh0KRppoT6povanlMe4U/0mRpURrhGJx9OsBm6zOrloFn8AA/aS50Z6y+mrPBuV4e3q8NzM51/BHuXcle84F7FEJoH8CJKO8EEvErgkTGPro9Xvp5mRC6Qd8Nzu5SmhY1XKeoQkhecW+QHPj7SYzIQH27IMSPq5R2oYoPPhqXbA9n9VxGU0r/bHXFxAfD59VfyH5wn1cNHux0KPPF15tzusxpWBRzJA5lfIzLT2tu/Q55rGbdlCtvwp282GSHgTN60XIK6xlfGcTVE8ntnu/P47Bg/qA5d7JG+6EufTp/8pF98Jq0m15agYYBohhzID5D9dmNX+YA94copYliT6+/17OwNkWH+YYCHac+D/FELdb4HO9vw74Ipf3Zdh/z7hrW8mMJmGsPKXM0ePN2yc46jkZVf7zGWbXd3Sc2y0OjQLjGX2sOkUXW7XklcThep1tyOjCg=
before_install:
  - |
    if [[ $JHI_JDK = '8' ]]; then
      echo '*** Using OpenJDK 8'
    else
      echo '*** Using OpenJDK 11 by default'
      sudo add-apt-repository ppa:openjdk-r/ppa -y
      sudo apt-get update -q
      sudo apt-get install -y openjdk-11-jdk -y
      sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
      java -version
    fi
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - chmod +x gradlew
  - './gradlew checkstyleNohttp'
  - './gradlew clean test integrationTest'
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then ./gradlew sonarqube --no-daemon -Dsonar.organization=handspy
    -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN; fi
  - './gradlew bootJar -Pprod -x test'
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
