package pt.up.hs.linguistics.domain.enumeration;

/**
 * The TertiaryEmotion enumeration.
 */
public enum TertiaryEmotion {
    AUDACITY, EXTROVERSION, TRANQUILITY, RELAXATION, HAPPINESS, PLEASURE, LAUGHTER, MENTAL_HEALTH, BALANCE, JOY, VIVACITY, ALERT, APPEASEMENT, LIBERATION, ESTEEM, SATIETY, LIKE, LOVE, DESIRE, ADMIRATION, ATTRACTION, GOODNESS, SWEETNESS, PATIENCE, HUMILITY, INTROVERSION, PAVOR, UNEASINESS, ANGUISH, CRY, PAIN, DRAMA, IMBALANCE, MENTAL_DISEASE, APATHY, FATIGUE, SADNESS, REMORSE, SHAKE, DISLIKE, FRUSTRATION, HUMILIATION, PRIDE, RAGE, ANGER, CRUELTY, IRRITATION, CONTEMPT, DISGUST, RESENTMENT
}
